name: Docker
on:
  push:
    branches: [ "development" ]
    
jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          docker build . -t brunovbs/${{ github.repository }}:latest
      - name: publish
        run: |
          docker login -u brunovbs -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push brunovbs/${{ github.repository }}:latest