name: Docker
on:
  push:
    branches: [ "development" ]
    
jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker build . -t brunovbs/$REPO_NAME:latest
      - name: publish
        run: |
          docker login -u brunovbs -p ${{ secrets.DOCKER_HUB_TOKEN }}
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker push brunovbs/$REPO_NAME:latest